site_name: Commander Challenges
site_url: https://chronistoftheblacksword.github.io/commander-challenges/
docs_dir: budget-challenge

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: green
  features:
    - navigation.top
    - search.suggest

nav:
  - The Challenge: index.md
